# Generated by GitHub Copilot - Sep-14-2026
"""LLM client astratto per EasyRead.

Espone una singola funzione :func:`chat` compatibile con qualunque
provider "OpenAI-compatible" (OpenRouter, Ollama locale, Groq, ecc.).

Cambiare provider = cambiare `LLM_PROVIDER` in `.env`. Nessuna modifica al codice.
"""

from __future__ import annotations

import os
from dataclasses import dataclass
from typing import Any

from dotenv import load_dotenv
from openai import OpenAI

load_dotenv()


@dataclass(frozen=True)
class LLMConfig:
    """Configurazione del provider LLM attivo."""

    provider: str
    base_url: str
    api_key: str
    model: str


def _load_config() -> LLMConfig:
    """Legge la configurazione LLM dalle variabili d'ambiente.

    Returns:
        LLMConfig con provider, endpoint, chiave e modello risolti.

    Security: la chiave API non deve mai finire nei log; non fare `print(cfg)`
    su config caricate — usare `provider` e `model` singolarmente.
    """
    provider = os.getenv("LLM_PROVIDER", "openrouter").strip().lower()

    if provider == "openrouter":
        return LLMConfig(
            provider="openrouter",
            base_url="https://openrouter.ai/api/v1",
            api_key=os.getenv("OPENROUTER_API_KEY", ""),
            model=os.getenv(
                "OPENROUTER_MODEL", "meta-llama/llama-3.3-70b-instruct:free"
            ),
        )

    if provider == "ollama":
        return LLMConfig(
            provider="ollama",
            base_url=os.getenv("OLLAMA_BASE_URL", "http://localhost:11434/v1"),
            api_key="ollama",  # Ollama ignora la chiave ma il client la richiede
            model=os.getenv("OLLAMA_MODEL", "qwen2.5:7b"),
        )

    raise ValueError(
        f"LLM_PROVIDER '{provider}' non supportato. Usa 'openrouter' o 'ollama'."
    )


_config: LLMConfig | None = None
_client: OpenAI | None = None


def get_config() -> LLMConfig:
    """Restituisce la configurazione LLM (cached).

    Returns:
        Istanza singleton di :class:`LLMConfig`.
    """
    global _config
    if _config is None:
        _config = _load_config()
    return _config


def _get_client() -> OpenAI:
    """Restituisce il client OpenAI-compatible (cached)."""
    global _client
    if _client is None:
        cfg = get_config()
        if not cfg.api_key:
            raise RuntimeError(
                f"API key mancante per provider '{cfg.provider}'. "
                "Controlla il file .env."
            )
        _client = OpenAI(base_url=cfg.base_url, api_key=cfg.api_key)
    return _client


def chat(
    system: str,
    user: str,
    *,
    temperature: float = 0.2,
    max_tokens: int = 1024,
    response_format: dict[str, Any] | None = None,
) -> str:
    """Invia una richiesta chat completion al provider configurato.

    Args:
        system: Prompt di sistema (istruzioni permanenti per l'agente).
        user: Messaggio utente / input concreto.
        temperature: 0.0-1.0. Più basso = più deterministico. Default 0.2
            per output stabili (importante per la semplificazione fedele).
        max_tokens: Tetto massimo dei token in output.
        response_format: Se fornito (es. ``{"type": "json_object"}``),
            il modello risponderà in JSON strutturato.

    Returns:
        Il contenuto testuale della risposta.

    Security: né `system` né `user` sono mai loggati in chiaro.
    L'input utente deve essere trattato come non fidato (prompt injection
    resistente lato prompt: vedi agents/*/prompt.md).
    """
    client = _get_client()
    cfg = get_config()

    kwargs: dict[str, Any] = {
        "model": cfg.model,
        "messages": [
            {"role": "system", "content": system},
            {"role": "user", "content": user},
        ],
        "temperature": temperature,
        "max_tokens": max_tokens,
    }
    if response_format is not None:
        kwargs["response_format"] = response_format

    resp = client.chat.completions.create(**kwargs)
    content = resp.choices[0].message.content or ""
    return content.strip()
