# Generated by GitHub Copilot - Sep-14-2026
"""Modelli dati condivisi tra agenti EasyRead.

Definisce le strutture Pydantic che rappresentano il risultato di ciascun
agente e il risultato finale mostrato all'utente.
"""

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, Field


DocumentType = Literal[
    "avviso_bonario",
    "cartella_pagamento",
    "comunicazione_irregolarita",
    "richiesta_documenti",
    "rimborso",
    "altro",
]


class Classification(BaseModel):
    """Output del Classifier Agent."""

    document_type: DocumentType = Field(
        description="Tipo di documento AdE riconosciuto"
    )
    confidence: float = Field(
        ge=0.0, le=1.0, description="Confidenza del riconoscimento (0-1)"
    )
    human_label: str = Field(
        description="Etichetta leggibile in italiano semplice"
    )


class Action(BaseModel):
    """Singola azione che l'utente deve/può compiere."""

    what: str = Field(description="Cosa fare, in italiano semplice")
    deadline: str | None = Field(
        default=None, description="Scadenza in formato leggibile (es. '30/10/2026')"
    )
    priority: Literal["alta", "media", "bassa"] = Field(default="media")


class ActionPlan(BaseModel):
    """Output dell'Action Agent."""

    summary: str = Field(
        description="Sintesi in 1-2 frasi di cosa è successo"
    )
    actions: list[Action] = Field(default_factory=list)
    amount_due: str | None = Field(
        default=None, description="Importo da pagare, se presente (es. '243,50 €')"
    )
    payment_deadline: str | None = Field(
        default=None, description="Scadenza di pagamento, se presente"
    )
    consequences_if_ignored: str | None = Field(
        default=None,
        description="Cosa succede se l'utente ignora il documento",
    )


class SafetyReport(BaseModel):
    """Output del Safety Agent."""

    numbers_match: bool = Field(
        description="True se tutti i numeri (importi) nell'output derivano dall'originale"
    )
    dates_match: bool = Field(
        description="True se tutte le date nell'output derivano dall'originale"
    )
    warnings: list[str] = Field(
        default_factory=list,
        description="Avvisi da mostrare all'utente (es. 'importo non chiaro')",
    )
    confidence: Literal["alta", "media", "bassa"] = Field(
        description="Confidenza complessiva sulla semplificazione"
    )


class EasyReadResult(BaseModel):
    """Risultato completo mostrato in UI."""

    original_text: str
    classification: Classification
    simplified_text: str
    action_plan: ActionPlan
    safety: SafetyReport
